Also include C++ tarballs in releases
lab-cosmo/metatensor pull request #386
Opened 2023-09-27 15:02 UTC by Luthaf

This mean making a release is just a matter of pushing a tag to the repo. Distribution of the C++ parts of metatensor (e.g. pre-built versions in conda-forge) will then be able to use the tarball attached to the release as the sources to build.

2023-09-27 15:19 UTC, Luthaf commented
Ok, the comment above is not added for PR from a fork because of https://github.com/orgs/community/discussions/25220. I'll see what we can/should do about this later.

2023-09-29 07:04 UTC, agoscinski requested changes
Just some suggested changes. Looks good.

2023-09-29 07:04 UTC, agoscinski commented on scripts/package-torch.sh
> +./scripts/n-commits-since-last-tag.py "metatensor-torch-v" > "$TMP_DIR/$ARCHIVE_NAME/cmake/n_commits_since_last_tag"
maybe can you add a small comment that the produced file is used during building?

2023-09-29 09:27 UTC, Luthaf commented on .github/workflows/build-wheels.yml
> +    tags: ["*"]
just consistency with the docs building file which also runs on tags

2023-09-29 11:17 UTC, agoscinski approved these changes
Seems like there is only a problem with readthedocs, PR looks fine.

2023-09-29 11:51 UTC, merged