Deploy documentation on a separate repository
lab-cosmo/metatensor pull request #609
Opened 2024-05-03 16:39 UTC by Luthaf

This will help keeping the size of this repository under control. The documentation will be deployed to https://github.com/lab-cosmo/metatensor-docs, which is then served at https://docs.metatensor.org/

This does not change how developers write the documentation or build it locally, only how we create the public documentation website.

# Contributor (creator of pull-request) checklist

 - [ ] Tests updated (for new features and bugfixes)?
 - [ ] Documentation updated (for new features)?
 - [ ] Issue referenced (for PRs that solve an issue)?

# Reviewer checklist

 - [ ] CHANGELOG updated with public API or any other important changes?

2024-05-08 11:08 UTC, Luthaf commented
Regarding the update: I'll replace all the files in this repo's gh-pages (i.e. stuff served at https://lab-cosmo.github.io/metatensor/) with a redirect to the new docs, and we can remove the old pages in ~6 months.

2024-05-13 09:06 UTC, PicoCentauri requested changes

2024-05-13 09:06 UTC, PicoCentauri commented on docs/extensions/versions_list.py
> +DOC_ROOT = "https://doc.metatensor.org/"
```suggestion
DOC_ROOT = "https://docs.metatensor.org/"
```

2024-05-13 09:18 UTC, Luthaf commented on docs/extensions/versions_list.py
> +DOC_ROOT = "https://doc.metatensor.org/"
whoops, thanks!

2024-05-13 11:39 UTC, PicoCentauri approved these changes

2024-05-13 11:49 UTC, merged